/** # Departamentos
 * Devuelve un array con todos los Departmentos de Guatemala
 */
const departamentos = [
  "Alta Verapaz",
  "Baja Verapaz",
  "Chimaltenango",
  "Chiquimula",
  "El Progreso",
  "Escuintla",
  "Guatemala",
  "Huehuetenango",
  "Izabal",
  "Jalapa",
  "Jutiapa",
  "Petén",
  "Quetzaltenango",
  "Quiché",
  "Retalhuleu",
  "Sacatepéquez",
  "San Marcos",
  "Santa Rosa",
  "Sololá",
  "Suchitepéquez",
  "Totonicapán",
  "Zacapa",
]

/** # Municipios
 * Devuelve un objeto que tiene como propiadedades los nombres de los departamentos, sin diacríticos.
 */
const municipios = {
  "altaverapaz": [
    "Cobán",
    "Chahal",
    "Chisec",
    "Fray Bartolomé de Las Casas",
    "Panzós",
    "Raxruhá",
    "San Agustín Lanquín",
    "San Cristóbal Verapaz",
    "San Juan Chamelco",
    "San Miguel Tucurú",
    "San Pedro Carchá",
    "Santa Catalina La Tinta",
    "Santa Cruz Verapaz",
    "Santa María Cahabón",
    "Senahú",
    "Tactic",
    "Tamahú",
  ],
  "bajaverapaz": [
    "Salamá",
    "Cubulco",
    "Granados",
    "Purulhá",
    "Rabinal",
    "San Jerónimo",
    "San Miguel Chicaj",
    "Santa Cruz El Chol",
  ],
  "chimaltenango": [
    "Chimaltenango",
    "Acatenango",
    "El Tejar",
    "Parramos",
    "Patzicía",
    "Patzún",
    "San Andrés Itzapa",
    "San José Poaquil",
    "San Juan Comalapa",
    "San Martín Jilotepeque",
    "San Miguel Pochuta",
    "San Pedro Yepocapa",
    "Santa Apolonia",
    "Santa Cruz Balanyá",
    "Tecpán Guatemala",
    "Zaragoza",
  ],
  "chiquimula": [
    "Chiquimula",
    "Camotán",
    "Concepción Las Minas",
    "Esquipulas",
    "Ipala",
    "Jocotán",
    "Olopa",
    "Quezaltepeque",
    "San Jacinto",
    "San José La Arada",
    "San Juan Ermita",
  ],
  "elprogreso": [
    "Guastatoya",
    "El Jícaro",
    "Morazán",
    "San Agustín Acasaguastlan",
    "San Antonio La Paz",
    "San Cristóbal Acasaguastlan",
    "Sanarate",
    "Sansare",
  ],
  "escuintla": [
    "Escuintla",
    "Guanagazapa",
    "Iztapa",
    "La Democracia",
    "La Gomera",
    "Masagua",
    "Nueva Concepción",
    "Palín",
    "San José",
    "San Vicente Pacaya",
    "Santa Lucía Cotzumalguapa",
    "Sipacate",
    "Siquinalá",
    "Tiquisate",
  ],
  "guatemala": [
    "Guatemala",
    "Amatitlán",
    "Chinautla",
    "Chuarrancho",
    "Fraijanes",
    "Mixco",
    "Palencia",
    "San José del Golfo",
    "San José Pinula",
    "San Juan Sacatepéquez",
    "San Miguel Petapa",
    "San Pedro Ayampuc",
    "San Pedro Sacatepéquez",
    "San Raymundo",
    "Santa Catarina Pinula",
    "Villa Canales",
    "Villa Nueva",
  ],
  "huehuetenango": [
    "Huehuetenango",
    "Aguacatán",
    "Chiantla",
    "Colotenango",
    "Concepción Huista",
    "Cuilco",
    "Jacaltenango",
    "La Democracia",
    "La Libertad",
    "Malacatancito",
    "Nentón",
    "Petatán",
    "San Antonio Huista",
    "San Gaspar Ixchil",
    "San Ildefonso Ixtahuacán",
    "San Juan Atitán",
    "San Juan Ixcoy",
    "San Mateo Ixtatán",
    "San Miguel Acatán",
    "San Pedro Necta",
    "San Pedro Soloma",
    "San Rafael La Independencia",
    "San Rafael Petzal",
    "San Sebastián Coatán",
    "San Sebastián Huehuetenango",
    "Santa Ana Huista",
    "Santa Bárbara",
    "Santa Cruz Barillas",
    "Santa Eulalia",
    "Santiago Chimaltenango",
    "Tectitán",
    "Todos Santos Cuchumatán",
    "Unión Cantinil",
  ],
  "izabal": [
    "Puerto Barrios",
    "El Estor",
    "Livingston",
    "Los Amates",
    "Morales",
  ],
  "jalapa": [
    "Jalapa",
    "Mataquescuintla",
    "Monjas",
    "San Carlos Alzatate",
    "San Luis Jilotepeque",
    "San Manuel Chaparrón",
    "San Pedro Pinula",
  ],
  "jutiapa": [
    "Jutiapa",
    "Agua Blanca",
    "Asunción Mita",
    "Atescatempa",
    "Comapa",
    "Conguaco",
    "El Adelanto",
    "El Progreso",
    "Jalpatagua",
    "Jerez",
    "Moyuta",
    "Pasaco",
    "Quesada",
    "San José Acatempa",
    "Santa Catarina Mita",
    "Yupiltepeque",
    "Zapotitlán",
  ],
  "peten": [
    "Flores",
    "Dolores",
    "El Chal",
    "La Libertad",
    "Las Cruces",
    "Melchor de Mencos",
    "Poptún",
    "San Andrés",
    "San Benito",
    "San Francisco",
    "San José",
    "San Luis",
    "Santa Ana",
    "Sayaxché",
  ],
  "quetzaltenango": [
    "Quetzaltenango",
    "Almolonga",
    "Cabricán",
    "Cajolá",
    "Cantel",
    "Coatepeque",
    "Colomba Costa Cuca",
    "Concepción Chiquirichapa",
    "El Palmar",
    "Flores Costa Cuca",
    "Génova",
    "Huitán",
    "La Esperanza",
    "Palestina de Los Altos",
    "Salcajá",
    "San Carlos Sija",
    "San Francisco La Unión",
    "San Juan Olintepeque",
    "San Juan Ostuncalco",
    "San Martín Sacatepéquez",
    "San Mateo",
    "San Miguel Sigüilá",
    "Sibilia",
    "Zunil",
  ],
  "quiche": [
    "Santa Cruz del Quiché",
    "Canillá",
    "Chajul",
    "Chicamán",
    "Chiché",
    "Chinique",
    "Cunén",
    "Joyabaj",
    "Pachalum",
    "Patzité",
    "Playa Grande Ixcán",
    "Sacapulas",
    "San Andrés Sajcabajá",
    "San Antonio Ilotenango",
    "San Bartolomé Jocotenango",
    "San Juan Cotzal",
    "San Miguel Uspantán",
    "San Pedró Jocopilas",
    "Santa María Nebaj",
    "Santo Tomás Chichicastenango",
    "Zacualpa",
  ],
  "retalhuleu": [
    "Retalhuleu",
    "Champerico",
    "El Asintal",
    "Nuevo San Carlos",
    "San Andrés Villa Seca",
    "San Felipe",
    "San Martín Zapotitlán",
    "San Sebastián",
    "Santa Cruz Muluá",
  ],
  "sacatepequez": [
    "Antigua Guatemala",
    "Ciudad Vieja",
    "Jocotenango",
    "Magdalena Milpas Altas",
    "Pastores",
    "San Antonio Aguas Calientes",
    "San Bartolomé Milpas Altas",
    "San Juan Alotenango",
    "San Lucas Sacatepéquez",
    "San Miguel Dueñas",
    "Santa Catarina Barahona",
    "Santa Lucía Milpas Altas",
    "Santa María de Jesús",
    "Santiago Sacatepéquez",
    "Santo Domingo Xenacoj",
    "Sumpango",
  ],
  "sanmarcos": [
    "San Marcos",
    "Ayutla",
    "Catarina",
    "Comitancillo",
    "Concepción Tutuapa",
    "El Quetzal",
    "El Tumbador",
    "Esquipulas Palo Gordo",
    "Ixchiguán",
    "La Blanca",
    "La Reforma",
    "Malacatán",
    "Nuevo Progreso",
    "Ocós",
    "Pajapita",
    "Río Blanco",
    "San Antonio Sacatepéquez",
    "San Cristobal Cucho",
    "San José El Rodeo",
    "San José Ojetenam",
    "San Lorenzo",
    "San Miguel Ixtahuacán",
    "San Pablo",
    "San Pedro Sacatepéquez",
    "San Rafael Pie de La Cuesta",
    "Sibinal",
    "Sipacapa",
    "Tacaná",
    "Tajumulco",
    "Tejutla",
  ],
  "santarosa": [
    "Cuilapa",
    "Barberena",
    "Casillas",
    "Chiquimulilla",
    "Guazacapán",
    "Nueva Santa Rosa",
    "Oratorio",
    "Pueblo Nuevo Viñas",
    "San Juan Tecuaco",
    "San Rafael Las Flores",
    "Santa Cruz Naranjo",
    "Santa María Ixhuatán",
    "Santa Rosa de Lima",
    "Taxisco",
  ],
  "solola": [
    "Sololá",
    "Concepción",
    "Nahualá",
    "Panajachel",
    "San Andrés Semetabaj",
    "San Antonio Palopó",
    "San José Chacayá",
    "San Juan La Laguna",
    "San Lucas Tolimán",
    "San Marcos La Laguna",
    "San Pablo La Laguna",
    "San Pedro La Laguna",
    "Santa Catarina Ixtahuacán",
    "Santa Catarina Palopó",
    "Santa Clara La Laguna",
    "Santa Cruz La Laguna",
    "Santa Lucía Utatlán",
    "Santa María Visitación",
    "Santiago Atitlán",
  ],
  "suchitepequez": [
    "Mazatenango",
    "Chicacao",
    "Cuyotenango",
    "Patulul",
    "Pueblo Nuevo",
    "Río Bravo",
    "Samayac",
    "San Antonio Suchitepéquez",
    "San Bernardino",
    "San Francisco Zapotitlán",
    "San Gabriel",
    "San José El Ídolo",
    "San José La Máquina",
    "San Juan Bautista",
    "San Lorenzo",
    "San Miguel Panán",
    "San Pablo Jocopilas",
    "Santa Bárbara",
    "Santo Domingo Suchitepéquez",
    "Santo Tomás La Unión",
    "Zunilito",
  ],
  "totonicapan": [
    "Totonicapán",
    "Momostenango",
    "San Andrés Xecul",
    "San Bartolo Aguas Calientes",
    "San Cristóbal Totonicapán",
    "San Francisco El Alto",
    "Santa Lucía La Reforma",
    "Santa María Chiquimula",
  ],
  "zacapa": [
    "Zacapa",
    "Estanzuela",
    "Río Hondo",
    "Gualán",
    "Teculután",
    "Usumatlán",
    "Cabañas",
    "San Diego",
    "La Unión",
    "Huité",
    "San Jorge",
  ],
}

/** # Objetos de Municipios
 *  Devuelve como resultado
 */
const municipiosObj = {
  "Alta Verapaz": [
    "Cobán",
    "Chahal",
    "Chisec",
    "Fray Bartolomé de Las Casas",
    "Panzós",
    "Raxruhá",
    "San Agustín Lanquín",
    "San Cristóbal Verapaz",
    "San Juan Chamelco",
    "San Miguel Tucurú",
    "San Pedro Carchá",
    "Santa Catalina La Tinta",
    "Santa Cruz Verapaz",
    "Santa María Cahabón",
    "Senahú",
    "Tactic",
    "Tamahú",
  ],
  "Baja Verapaz": [
    "Salamá",
    "Cubulco",
    "Granados",
    "Purulhá",
    "Rabinal",
    "San Jerónimo",
    "San Miguel Chicaj",
    "Santa Cruz El Chol",
  ],
  "Chimaltenango": [
    "Chimaltenango",
    "Acatenango",
    "El Tejar",
    "Parramos",
    "Patzicía",
    "Patzún",
    "San Andrés Itzapa",
    "San José Poaquil",
    "San Juan Comalapa",
    "San Martín Jilotepeque",
    "San Miguel Pochuta",
    "San Pedro Yepocapa",
    "Santa Apolonia",
    "Santa Cruz Balanyá",
    "Tecpán Guatemala",
    "Zaragoza",
  ],
  "Chiquimula": [
    "Chiquimula",
    "Camotán",
    "Concepción Las Minas",
    "Esquipulas",
    "Ipala",
    "Jocotán",
    "Olopa",
    "Quezaltepeque",
    "San Jacinto",
    "San José La Arada",
    "San Juan Ermita",
  ],
  "El Progreso": [
    "Guastatoya",
    "El Jícaro",
    "Morazán",
    "San Agustín Acasaguastlan",
    "San Antonio La Paz",
    "San Cristóbal Acasaguastlan",
    "Sanarate",
    "Sansare",
  ],
  "Escuintla": [
    "Escuintla",
    "Guanagazapa",
    "Iztapa",
    "La Democracia",
    "La Gomera",
    "Masagua",
    "Nueva Concepción",
    "Palín",
    "San José",
    "San Vicente Pacaya",
    "Santa Lucía Cotzumalguapa",
    "Sipacate",
    "Siquinalá",
    "Tiquisate",
  ],
  "Guatemala": [
    "Guatemala",
    "Amatitlán",
    "Chinautla",
    "Chuarrancho",
    "Fraijanes",
    "Mixco",
    "Palencia",
    "San José del Golfo",
    "San José Pinula",
    "San Juan Sacatepéquez",
    "San Miguel Petapa",
    "San Pedro Ayampuc",
    "San Pedro Sacatepéquez",
    "San Raymundo",
    "Santa Catarina Pinula",
    "Villa Canales",
    "Villa Nueva",
  ],
  "Huehuetenango": [
    "Huehuetenango",
    "Aguacatán",
    "Chiantla",
    "Colotenango",
    "Concepción Huista",
    "Cuilco",
    "Jacaltenango",
    "La Democracia",
    "La Libertad",
    "Malacatancito",
    "Nentón",
    "Petatán",
    "San Antonio Huista",
    "San Gaspar Ixchil",
    "San Ildefonso Ixtahuacán",
    "San Juan Atitán",
    "San Juan Ixcoy",
    "San Mateo Ixtatán",
    "San Miguel Acatán",
    "San Pedro Necta",
    "San Pedro Soloma",
    "San Rafael La Independencia",
    "San Rafael Petzal",
    "San Sebastián Coatán",
    "San Sebastián Huehuetenango",
    "Santa Ana Huista",
    "Santa Bárbara",
    "Santa Cruz Barillas",
    "Santa Eulalia",
    "Santiago Chimaltenango",
    "Tectitán",
    "Todos Santos Cuchumatán",
    "Unión Cantinil",
  ],
  "Izabal": [
    "Puerto Barrios",
    "El Estor",
    "Livingston",
    "Los Amates",
    "Morales",
  ],
  "Jalapa": [
    "Jalapa",
    "Mataquescuintla",
    "Monjas",
    "San Carlos Alzatate",
    "San Luis Jilotepeque",
    "San Manuel Chaparrón",
    "San Pedro Pinula",
  ],
  "Jutiapa": [
    "Jutiapa",
    "Agua Blanca",
    "Asunción Mita",
    "Atescatempa",
    "Comapa",
    "Conguaco",
    "El Adelanto",
    "El Progreso",
    "Jalpatagua",
    "Jerez",
    "Moyuta",
    "Pasaco",
    "Quesada",
    "San José Acatempa",
    "Santa Catarina Mita",
    "Yupiltepeque",
    "Zapotitlán",
  ],
  "Petén": [
    "Flores",
    "Dolores",
    "El Chal",
    "La Libertad",
    "Las Cruces",
    "Melchor de Mencos",
    "Poptún",
    "San Andrés",
    "San Benito",
    "San Francisco",
    "San José",
    "San Luis",
    "Santa Ana",
    "Sayaxché",
  ],
  "Quetzaltenango": [
    "Quetzaltenango",
    "Almolonga",
    "Cabricán",
    "Cajolá",
    "Cantel",
    "Coatepeque",
    "Colomba Costa Cuca",
    "Concepción Chiquirichapa",
    "El Palmar",
    "Flores Costa Cuca",
    "Génova",
    "Huitán",
    "La Esperanza",
    "Palestina de Los Altos",
    "Salcajá",
    "San Carlos Sija",
    "San Francisco La Unión",
    "San Juan Olintepeque",
    "San Juan Ostuncalco",
    "San Martín Sacatepéquez",
    "San Mateo",
    "San Miguel Sigüilá",
    "Sibilia",
    "Zunil",
  ],
  "Quiché": [
    "Santa Cruz del Quiché",
    "Canillá",
    "Chajul",
    "Chicamán",
    "Chiché",
    "Chinique",
    "Cunén",
    "Joyabaj",
    "Pachalum",
    "Patzité",
    "Playa Grande Ixcán",
    "Sacapulas",
    "San Andrés Sajcabajá",
    "San Antonio Ilotenango",
    "San Bartolomé Jocotenango",
    "San Juan Cotzal",
    "San Miguel Uspantán",
    "San Pedró Jocopilas",
    "Santa María Nebaj",
    "Santo Tomás Chichicastenango",
    "Zacualpa",
  ],
  "Retalhuleu": [
    "Retalhuleu",
    "Champerico",
    "El Asintal",
    "Nuevo San Carlos",
    "San Andrés Villa Seca",
    "San Felipe",
    "San Martín Zapotitlán",
    "San Sebastián",
    "Santa Cruz Muluá",
  ],
  "Sacatepéquez": [
    "Antigua Guatemala",
    "Ciudad Vieja",
    "Jocotenango",
    "Magdalena Milpas Altas",
    "Pastores",
    "San Antonio Aguas Calientes",
    "San Bartolomé Milpas Altas",
    "San Juan Alotenango",
    "San Lucas Sacatepéquez",
    "San Miguel Dueñas",
    "Santa Catarina Barahona",
    "Santa Lucía Milpas Altas",
    "Santa María de Jesús",
    "Santiago Sacatepéquez",
    "Santo Domingo Xenacoj",
    "Sumpango",
  ],
  "San Marcos": [
    "San Marcos",
    "Ayutla",
    "Catarina",
    "Comitancillo",
    "Concepción Tutuapa",
    "El Quetzal",
    "El Tumbador",
    "Esquipulas Palo Gordo",
    "Ixchiguán",
    "La Blanca",
    "La Reforma",
    "Malacatán",
    "Nuevo Progreso",
    "Ocós",
    "Pajapita",
    "Río Blanco",
    "San Antonio Sacatepéquez",
    "San Cristobal Cucho",
    "San José El Rodeo",
    "San José Ojetenam",
    "San Lorenzo",
    "San Miguel Ixtahuacán",
    "San Pablo",
    "San Pedro Sacatepéquez",
    "San Rafael Pie de La Cuesta",
    "Sibinal",
    "Sipacapa",
    "Tacaná",
    "Tajumulco",
    "Tejutla",
  ],
  "Santa Rosa": [
    "Cuilapa",
    "Barberena",
    "Casillas",
    "Chiquimulilla",
    "Guazacapán",
    "Nueva Santa Rosa",
    "Oratorio",
    "Pueblo Nuevo Viñas",
    "San Juan Tecuaco",
    "San Rafael Las Flores",
    "Santa Cruz Naranjo",
    "Santa María Ixhuatán",
    "Santa Rosa de Lima",
    "Taxisco",
  ],
  "Sololá": [
    "Sololá",
    "Concepción",
    "Nahualá",
    "Panajachel",
    "San Andrés Semetabaj",
    "San Antonio Palopó",
    "San José Chacayá",
    "San Juan La Laguna",
    "San Lucas Tolimán",
    "San Marcos La Laguna",
    "San Pablo La Laguna",
    "San Pedro La Laguna",
    "Santa Catarina Ixtahuacán",
    "Santa Catarina Palopó",
    "Santa Clara La Laguna",
    "Santa Cruz La Laguna",
    "Santa Lucía Utatlán",
    "Santa María Visitación",
    "Santiago Atitlán",
  ],
  "Suchitepéquez": [
    "Mazatenango",
    "Chicacao",
    "Cuyotenango",
    "Patulul",
    "Pueblo Nuevo",
    "Río Bravo",
    "Samayac",
    "San Antonio Suchitepéquez",
    "San Bernardino",
    "San Francisco Zapotitlán",
    "San Gabriel",
    "San José El Ídolo",
    "San José La Máquina",
    "San Juan Bautista",
    "San Lorenzo",
    "San Miguel Panán",
    "San Pablo Jocopilas",
    "Santa Bárbara",
    "Santo Domingo Suchitepéquez",
    "Santo Tomás La Unión",
    "Zunilito",
  ],
  "Totonicapán": [
    "Totonicapán",
    "Momostenango",
    "San Andrés Xecul",
    "San Bartolo Aguas Calientes",
    "San Cristóbal Totonicapán",
    "San Francisco El Alto",
    "Santa Lucía La Reforma",
    "Santa María Chiquimula",
  ],
  "Zacapa": [
    "Zacapa",
    "Estanzuela",
    "Río Hondo",
    "Gualán",
    "Teculután",
    "Usumatlán",
    "Cabañas",
    "San Diego",
    "La Unión",
    "Huité",
    "San Jorge",
  ],
}
/** # Población por departamento
 * Devuelve como resultado un entero con la catidad total de la población por departamento, sin diacríticos.
 */
const poblacionDepto = {
  "altaverapaz": 1215038,
  "bajaverapaz": 299476,
  "chimaltenango": 615776,
  "chiquimula": 415063,
  "elprogreso": 176632,
  "escuintla": 733181,
  "guatemala": 3015081,
  "huehuetenango": 1170669,
  "izabal": 408688,
  "jalapa": 342923,
  "jutiapa": 488395,
  "peten": 545600,
  "quetzaltenango": 799101,
  "quiche": 949261,
  "retalhuleu": 326828,
  "sacatepequez": 330469,
  "sanmarcos": 1032277,
  "santarosa": 396607,
  "solola": 421583,
  "suchitepequez": 554695,
  "totonicapan": 418569,
  "zacapa": 245374,
}

/** # Población por departamento
 *  Devuelve como resultado un entero con la catidad total de la población por departamento
 */
const poblacionDeptoObj = {
  "Alta Verapaz": 1215038,
  "Baja Verapaz": 299476,
  "Chimaltenango": 615776,
  "Chiquimula": 415063,
  "El Progreso": 176632,
  "Escuintla": 733181,
  "Guatemala": 3015081,
  "Huehuetenango": 1170669,
  "Izabal": 408688,
  "Jalapa": 342923,
  "Jutiapa": 488395,
  "Petén": 545600,
  "Quetzaltenango": 799101,
  "Quiché": 949261,
  "Retalhuleu": 326828,
  "Sacatepéquez": 330469,
  "San Marcos": 1032277,
  "Santa Rosa": 396607,
  "Sololá": 421583,
  "Suchitepéquez": 554695,
  "Totonicapán": 418569,
  "Zacapa": 245374,
}

module.exports = {
  departamentos,
  municipios,
  municipiosObj,
  poblacionDepto,
  poblacionDeptoObj
}