const departamentos = [
  "Alta Verapaz",
  "Baja Verapaz",
  "Chimaltenango",
  "Chiquimula",
  "El Progreso",
  "Escuintla",
  "Guatemala",
  "Huehuetenango",
  "Izabal",
  "Jalapa",
  "Jutiapa",
  "Petén",
  "Quetzaltenango",
  "Quiché",
  "Retalhuleu",
  "Sacatepéquez",
  "San Marcos",
  "Santa Rosa",
  "Sololá",
  "Suchitepéquez",
  "Totonicapán",
  "Zacapa",
]

const municipios = {
  "altaverapaz": [
    "Cobán",
    "Chahal",
    "Chisec",
    "Fray Bartolomé de las Casas",
    "Lanquín",
    "Panzos",
    "San Cristobal Verapaz",
    "San Miguel Tucurú",
    "San Pedro Carchá",
    "SanJuan Chamelco",
    "Santa Catarina La Tinta",
    "Santa Cruz Verapaz",
    "Santa María Cahabón",
    "Senahú",
    "Tactíc",
    "Tamahú",
  ],
  "bajaverapaz": [
    "Salamá",
    "Cubulco",
    "Granados",
    "Purulhá",
    "Rabinal",
    "San Jerónimo",
    "San Miguel Chicaj",
    "Santa Cruz El Chol",
  ],
  "chimaltenango": [
    "Chimaltenango",
    "Acatenango",
    "El Tejar",
    "Parramos",
    "Patzicia",
    "Patzun",
    "San Andrés Itzapa",
    "San José Poaquil",
    "San Juan Comalapa",
    "San Martín Jilotepeque",
    "San Miguel Pochuta",
    "San Pedro Yepocapa",
    "Santa Apolonia",
    "Santa Cruz Balanyá",
    "Tecpán Guatemala",
    "Zaragoza",
  ],
  "chiquimula": [
    "Chiquimula",
    "Camotán",
    "Concepción Las Minas",
    "Esquipulas",
    "Ipala",
    "Jocotán",
    "Olopa",
    "Quezaltepeque",
    "San Jacinto",
    "San José La Arada",
    "San Juan Hermita",
  ],
  "elprogreso": [
    "Guastatoya",
    "El Jícaro",
    "Morazán",
    "San Agustín Acasaguastlan",
    "San Antonio La Paz",
    "San Cristóbal Acasaguastlan",
    "Sanarate",
    "Sansare",
  ],
  "escuintla": [
    "Escuintla",
    "Guanagazapa",
    "Iztapa",
    "La Democracia",
    "La Gomera",
    "Masagua",
    "Nueva Concepción",
    "Palín",
    "Pueblo Nuevo Tiquisate",
    "Puerto de San José",
    "San Vicente Pacaya",
    "Santa Lucía Cotzumalguapa",
    "Siquinalá",
  ],
  "guatemala": [
    "Guatemala",
    "Amatitlán",
    "Chinautla",
    "Chuarrancho",
    "Fraijanes",
    "Mixco",
    "Palencia",
    "San José del Golfo",
    "San José Pinula",
    "San Juan Sacatepequez",
    "San Miguel Petapa",
    "San Pedro Ayampuc",
    "San Pedro Sacatepequez",
    "San Raymundo",
    "Santa Catarina Pinula",
    "Villa Canales",
    "Villa Nueva",
  ],
  "huehuetenango": [
    "Huehuetenango",
    "Aguacatán",
    "Chiantla",
    "Colotenango",
    "Concepción Huista",
    "Cuilco",
    "Jacaltenango",
    "La Democracia",
    "La Libertad",
    "Malacatancito",
    "Nentón",
    "San Antonio Huista",
    "San Gaspar Ixchil",
    "San Ildelfonso Ixtahuac´ n",
    "San Juan Atitán",
    "San Juan Ixcoy",
    "San Mateo Ixtatán",
    "San Miguel Acatán",
    "San Pedro Necta",
    "San Pedro Soloma",
    "San Rafael La Independencia",
    "San Rafael Petzal",
    "San Sebastián Coatán",
    "San Sebastián Huehuetenango",
    "Santa Ana Huista",
    "Santa Bárbara",
    "Santa Cruz Barillas",
    "Santa Eulalia",
    "Santiago Chimaltenango",
    "Tectitán",
    "Todos Santos Chuchcumatán",
  ],
  "izabal": [
    "Puerto Barrios",
    "El Estor",
    "Livingston",
    "Los Amates",
    "Morales",
  ],
  "jalapa": [
    "Jalapa",
    "Mataquescuintla",
    "Monjas",
    "San Carlos Alzatate",
    "San Luis Jilotepeque",
    "San Manuel Chaparrón",
    "San Pedro Pinula",
  ],
  "jutiapa": [
    "Jutiapa",
    "Agua Blanca",
    "Asunción Mita",
    "Atescatempa",
    "Comapa",
    "Conguaco",
    "El Adelanto",
    "El Progreso",
    "Jalpatagua",
    "Jerez",
    "Moyuta",
    "Pasaco",
    "Quezada",
    "San José Acatempa",
    "Santa Catarina Mita",
    "Yupiltepeque",
    "Zapotitlán",
  ],
  "peten": [
    "Flores",
    "Dolores",
    "La Libertad",
    "Melchor de Mencos",
    "Poptún",
    "San Andrés",
    "San Benito",
    "San Francisco",
    "San José",
    "San Luis",
    "Santa Ana",
    "Sayaxche",
  ],
  "quetzaltenango": [
    "Quetzaltenango",
    "Almolonga",
    "Cabrican",
    "Cajola",
    "Cantel",
    "Coatepeque",
    "Colomba",
    "Concepción Chiquirichapa",
    "El Palmar",
    "Flores Costa Cuca",
    "Génova",
    "Huitán",
    "La Esperanza",
    "Olintepeque",
    "Palestina de los Altos",
    "Salcajá",
    "San Carlos Sija",
    "San Francisco La Unión",
    "San Juan Ostuncalco",
    "San Martín Sacatepequez",
    "San Mateo",
    "San Miguel Siguilça",
    "Sibilia",
    "Zunil",
  ],
  "quiche": [
    "Santa Cruz del Quiche",
    "Canilla",
    "Chajul",
    "Chicaman",
    "Chiche",
    "Chinique",
    "Cunén",
    "Joyabaj",
    "Pachalúm",
    "Patzité",
    "Playa Grande - Ixcán",
    "Sacapulas",
    "San Andrés Sajcabajá",
    "San Antonio Ilotenango",
    "San Bartolomé Jocotenango",
    "San Juan Cotzal",
    "San Miguel Uspatán",
    "San Pedro Jocopilas",
    "Santa María Nebaj",
    "Santo Tomás Chichicstenango",
    "Zacualpa",
  ],
  "retalhuleu": [
    "Retalhuelu",
    "Champerico",
    "El Asintal",
    "Nuevo San Carlos",
    "San Andrés Villa Seca",
    "San Felipe Retalhuleu",
    "San Martín Zapotitlán",
    "San Sebastián",
    "Santa Cruz Mulúa",
  ],
  "sacatepequez": [
    "Antigua Guatemala",
    "Ciudad Vieja",
    "Jocotenango",
    "Magdalena Milpas Altas",
    "Pastores",
    "San Antonio Aguas Calientes",
    "San Bartolomé Milpas Altas",
    "San Juan Alotenango",
    "San Lucas Sacatepequez",
    "San Miguel Dueñas",
    "Santa Catarina Barahona",
    "Santa Lucía Milpas Altas",
    "Santa María de Jesús",
    "Santiago Sacatepequez",
    "Santo Domingo Xenacoj",
    "Sumpango",
  ],
  "sanmarcos": [
    "San Marcos",
    "Ayutla",
    "Catarina",
    "Comitancillo",
    "Concepción Tutuapa",
    "El Quetzal",
    "El Tumbador",
    "Esquipulas Palo Gordo",
    "Ixchiguan",
    "La Reforma",
    "Malacatán",
    "Nuevo Progreso",
    "Ocos",
    "Pajapita",
    "Río Blanco",
    "San Antonio Sacatepéquez",
    "San Cristóbal Cucho",
    "San José El Rodeo",
    "San José Ojetenán",
    "San Lorenzo",
    "San Miguel Ixtahuacan",
    "San Pablo",
    "San Pedro Sacatepéquez",
    "San Rafael Pié de la Cuesta",
    "Sibinal",
    "Sipacapa",
    "Tacaná",
    "Tajumulco",
    "Tejutla",
  ],
  "santarosa": [
    "Cuilapa",
    "Berberena",
    "Casillas",
    "Chiquimulilla",
    "Guazacapán",
    "Nueva Santa Rosa",
    "Oratorio",
    "Pueblo Nuevo Viñas",
    "San Juan TEcuaco",
    "San Rafael Las Flores",
    "San Rosa de Lima",
    "Santa Cruz Naranjo",
    "Santa María Ixhuatan",
    "Taxisco",
  ],
  "solola": [
    "Sololá",
    "Concepción",
    "Nahualá",
    "Panajachel",
    "San Andrés Semetabaj",
    "San Antonio Palopó",
    "San José Chacaya",
    "San Juan La Laguna",
    "San Lucas Tolimán",
    "San Marcos La Laguna",
    "San Pedro La Laguna",
    "Santa Catarina Ixtahuacán",
    "Santa Catarina Palopó",
    "Santa Clara La Laguna",
    "Santa Cruz La Laguna",
    "Santa Lucía Utatlán",
    "Santa María Visitación",
    "Santiago Atitlán",
    "Sna Pablo La Laguna",
  ],
  "suchitepequez": [
    "Mazatenango",
    "Chicacao",
    "Cuyotenango",
    "Patulul",
    "Pueblo Nuevo Suchitepéquez",
    "Río Bravo",
    "Samayac",
    "San Antonio Suchitepéquez",
    "San Bernardino",
    "San Francisco Zapotitlán",
    "San Gabriel",
    "San José El Ídolo",
    "San Juan Bautista",
    "San Lorenzo",
    "San Miguel Panán",
    "San Pablo Jocopilas",
    "Santa Bárbara",
    "Santo Domingo Suchitepequez",
    "Santo Tomás La Unión",
    "Zunilito",
  ],
  "totonicapan": [
    "Totonicapán",
    "Momostenango",
    "San Andrés Xecul",
    "San Bartolo Aguas Calientes",
    "San Cristóbal Totonicapán",
    "San Francisco El Alto",
    "Santa Lucía La Reforma",
    "Santa María Chiquimula",
  ],
  "zacapa": [
    "Zacapa",
    "Cabañas",
    "Estanzuela",
    "Gualán",
    "Huité",
    "La Unión",
    "Río Hondo",
    "San Diego",
    "Teculután",
    "Usumatlán",
  ],
}

const municipiosObj = {
  "Alta Verapaz": [
    "Cobán",
    "Chahal",
    "Chisec",
    "Fray Bartolomé de las Casas",
    "Lanquín",
    "Panzos",
    "San Cristobal Verapaz",
    "San Miguel Tucurú",
    "San Pedro Carchá",
    "SanJuan Chamelco",
    "Santa Catarina La Tinta",
    "Santa Cruz Verapaz",
    "Santa María Cahabón",
    "Senahú",
    "Tactíc",
    "Tamahú",
  ],
  "Baja Verapaz": [
    "Salamá",
    "Cubulco",
    "Granados",
    "Purulhá",
    "Rabinal",
    "San Jerónimo",
    "San Miguel Chicaj",
    "Santa Cruz El Chol",
  ],
  "Chimaltenango": [
    "Chimaltenango",
    "Acatenango",
    "El Tejar",
    "Parramos",
    "Patzicia",
    "Patzun",
    "San Andrés Itzapa",
    "San José Poaquil",
    "San Juan Comalapa",
    "San Martín Jilotepeque",
    "San Miguel Pochuta",
    "San Pedro Yepocapa",
    "Santa Apolonia",
    "Santa Cruz Balanyá",
    "Tecpán Guatemala",
    "Zaragoza",
  ],
  "Chiquimula": [
    "Chiquimula",
    "Camotán",
    "Concepción Las Minas",
    "Esquipulas",
    "Ipala",
    "Jocotán",
    "Olopa",
    "Quezaltepeque",
    "San Jacinto",
    "San José La Arada",
    "San Juan Hermita",
  ],
  "El Progreso": [
    "Guastatoya",
    "El Jícaro",
    "Morazán",
    "San Agustín Acasaguastlan",
    "San Antonio La Paz",
    "San Cristóbal Acasaguastlan",
    "Sanarate",
    "Sansare",
  ],
  "Escuintla": [
    "Escuintla",
    "Guanagazapa",
    "Iztapa",
    "La Democracia",
    "La Gomera",
    "Masagua",
    "Nueva Concepción",
    "Palín",
    "Pueblo Nuevo Tiquisate",
    "Puerto de San José",
    "San Vicente Pacaya",
    "Santa Lucía Cotzumalguapa",
    "Siquinalá",
  ],
  "Guatemala": [
    "Guatemala",
    "Amatitlán",
    "Chinautla",
    "Chuarrancho",
    "Fraijanes",
    "Mixco",
    "Palencia",
    "San José del Golfo",
    "San José Pinula",
    "San Juan Sacatepequez",
    "San Miguel Petapa",
    "San Pedro Ayampuc",
    "San Pedro Sacatepequez",
    "San Raymundo",
    "Santa Catarina Pinula",
    "Villa Canales",
    "Villa Nueva",
  ],
  "Huehuetenango": [
    "Huehuetenango",
    "Aguacatán",
    "Chiantla",
    "Colotenango",
    "Concepción Huista",
    "Cuilco",
    "Jacaltenango",
    "La Democracia",
    "La Libertad",
    "Malacatancito",
    "Nentón",
    "San Antonio Huista",
    "San Gaspar Ixchil",
    "San Ildelfonso Ixtahuac´ n",
    "San Juan Atitán",
    "San Juan Ixcoy",
    "San Mateo Ixtatán",
    "San Miguel Acatán",
    "San Pedro Necta",
    "San Pedro Soloma",
    "San Rafael La Independencia",
    "San Rafael Petzal",
    "San Sebastián Coatán",
    "San Sebastián Huehuetenango",
    "Santa Ana Huista",
    "Santa Bárbara",
    "Santa Cruz Barillas",
    "Santa Eulalia",
    "Santiago Chimaltenango",
    "Tectitán",
    "Todos Santos Chuchcumatán",
  ],
  "Izabal": [
    "Puerto Barrios",
    "El Estor",
    "Livingston",
    "Los Amates",
    "Morales",
  ],
  "Jalapa": [
    "Jalapa",
    "Mataquescuintla",
    "Monjas",
    "San Carlos Alzatate",
    "San Luis Jilotepeque",
    "San Manuel Chaparrón",
    "San Pedro Pinula",
  ],
  "Jutiapa": [
    "Jutiapa",
    "Agua Blanca",
    "Asunción Mita",
    "Atescatempa",
    "Comapa",
    "Conguaco",
    "El Adelanto",
    "El Progreso",
    "Jalpatagua",
    "Jerez",
    "Moyuta",
    "Pasaco",
    "Quezada",
    "San José Acatempa",
    "Santa Catarina Mita",
    "Yupiltepeque",
    "Zapotitlán",
  ],
  "Petén": [
    "Flores",
    "Dolores",
    "La Libertad",
    "Melchor de Mencos",
    "Poptún",
    "San Andrés",
    "San Benito",
    "San Francisco",
    "San José",
    "San Luis",
    "Santa Ana",
    "Sayaxche",
  ],
  "Quetzaltenango": [
    "Quetzaltenango",
    "Almolonga",
    "Cabrican",
    "Cajola",
    "Cantel",
    "Coatepeque",
    "Colomba",
    "Concepción Chiquirichapa",
    "El Palmar",
    "Flores Costa Cuca",
    "Génova",
    "Huitán",
    "La Esperanza",
    "Olintepeque",
    "Palestina de los Altos",
    "Salcajá",
    "San Carlos Sija",
    "San Francisco La Unión",
    "San Juan Ostuncalco",
    "San Martín Sacatepequez",
    "San Mateo",
    "San Miguel Siguilça",
    "Sibilia",
    "Zunil",
  ],
  "Quiché": [
    "Santa Cruz del Quiche",
    "Canilla",
    "Chajul",
    "Chicaman",
    "Chiche",
    "Chinique",
    "Cunén",
    "Joyabaj",
    "Pachalúm",
    "Patzité",
    "Playa Grande - Ixcán",
    "Sacapulas",
    "San Andrés Sajcabajá",
    "San Antonio Ilotenango",
    "San Bartolomé Jocotenango",
    "San Juan Cotzal",
    "San Miguel Uspatán",
    "San Pedro Jocopilas",
    "Santa María Nebaj",
    "Santo Tomás Chichicstenango",
    "Zacualpa",
  ],
  "Retalhuleu": [
    "Retalhuelu",
    "Champerico",
    "El Asintal",
    "Nuevo San Carlos",
    "San Andrés Villa Seca",
    "San Felipe Retalhuleu",
    "San Martín Zapotitlán",
    "San Sebastián",
    "Santa Cruz Mulúa",
  ],
  "Sacatepéquez": [
    "Antigua Guatemala",
    "Ciudad Vieja",
    "Jocotenango",
    "Magdalena Milpas Altas",
    "Pastores",
    "San Antonio Aguas Calientes",
    "San Bartolomé Milpas Altas",
    "San Juan Alotenango",
    "San Lucas Sacatepequez",
    "San Miguel Dueñas",
    "Santa Catarina Barahona",
    "Santa Lucía Milpas Altas",
    "Santa María de Jesús",
    "Santiago Sacatepequez",
    "Santo Domingo Xenacoj",
    "Sumpango",
  ],
  "San Marcos": [
    "San Marcos",
    "Ayutla",
    "Catarina",
    "Comitancillo",
    "Concepción Tutuapa",
    "El Quetzal",
    "El Tumbador",
    "Esquipulas Palo Gordo",
    "Ixchiguan",
    "La Reforma",
    "Malacatán",
    "Nuevo Progreso",
    "Ocos",
    "Pajapita",
    "Río Blanco",
    "San Antonio Sacatepéquez",
    "San Cristóbal Cucho",
    "San José El Rodeo",
    "San José Ojetenán",
    "San Lorenzo",
    "San Miguel Ixtahuacan",
    "San Pablo",
    "San Pedro Sacatepéquez",
    "San Rafael Pié de la Cuesta",
    "Sibinal",
    "Sipacapa",
    "Tacaná",
    "Tajumulco",
    "Tejutla",
  ],
  "Santa Rosa": [
    "Cuilapa",
    "Berberena",
    "Casillas",
    "Chiquimulilla",
    "Guazacapán",
    "Nueva Santa Rosa",
    "Oratorio",
    "Pueblo Nuevo Viñas",
    "San Juan TEcuaco",
    "San Rafael Las Flores",
    "San Rosa de Lima",
    "Santa Cruz Naranjo",
    "Santa María Ixhuatan",
    "Taxisco",
  ],
  "Sololá": [
    "Sololá",
    "Concepción",
    "Nahualá",
    "Panajachel",
    "San Andrés Semetabaj",
    "San Antonio Palopó",
    "San José Chacaya",
    "San Juan La Laguna",
    "San Lucas Tolimán",
    "San Marcos La Laguna",
    "San Pedro La Laguna",
    "Santa Catarina Ixtahuacán",
    "Santa Catarina Palopó",
    "Santa Clara La Laguna",
    "Santa Cruz La Laguna",
    "Santa Lucía Utatlán",
    "Santa María Visitación",
    "Santiago Atitlán",
    "Sna Pablo La Laguna",
  ],
  "Suchitepéquez": [
    "Mazatenango",
    "Chicacao",
    "Cuyotenango",
    "Patulul",
    "Pueblo Nuevo Suchitepéquez",
    "Río Bravo",
    "Samayac",
    "San Antonio Suchitepéquez",
    "San Bernardino",
    "San Francisco Zapotitlán",
    "San Gabriel",
    "San José El Ídolo",
    "San Juan Bautista",
    "San Lorenzo",
    "San Miguel Panán",
    "San Pablo Jocopilas",
    "Santa Bárbara",
    "Santo Domingo Suchitepequez",
    "Santo Tomás La Unión",
    "Zunilito",
  ],
  "Totonicapán": [
    "Totonicapán",
    "Momostenango",
    "San Andrés Xecul",
    "San Bartolo Aguas Calientes",
    "San Cristóbal Totonicapán",
    "San Francisco El Alto",
    "Santa Lucía La Reforma",
    "Santa María Chiquimula",
  ],
  "Zacapa": [
    "Zacapa",
    "Cabañas",
    "Estanzuela",
    "Gualán",
    "Huité",
    "La Unión",
    "Río Hondo",
    "San Diego",
    "Teculután",
    "Usumatlán",
  ],
}

module.exports = {
  departamentos,
  municipios,
  municipiosObj
}